### ISSUE TITLE
Rearrange top bar buttons

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1100]
**update:** this ticket expands requirement #1038

Current top bar buttons include: Login/Logout, Share (schema and layout views only), Delete (edit view only), Preview, Save. 
Instead, the top bar should always display the following layout: More (ellipsis), Open, Save. 
![image](https://user-images.githubusercontent.com/1836666/70254537-3bba2200-1753-11ea-901d-3acc1a9b22e7.png)

- **More**: catch-all container for all the actions/buttons we don't want to display in the main menu
- **Open**: shows Launcher screen. Currently, this would be the only way to quickly access the launcher screen. 
- **Save**: performs save. 

### ToDo
- [ ] Move **Login/Logout** under the profile icon (#1014)
- [ ] Remove **Share** button. Its implementation is pending the release of Realms. When they are ready we will place it under the **More**
- [ ] Move **Delete** under **More**. It should also trigger warning and confirmation dialog before the action can be taken. 
- [ ] Remove **Preview** button
- [ ] Add **Duplicate** under **More**. This will create a duplicate of current card. All unsaved changes will be saved in the new card
- [ ] Add **Create new card from this** (exact name of the menu item tbd) under **More**. This will create a new card adopted from the current. System should ask whether to save changes. If yes - changes would be saved before adopting. If not - changes would be carried over to the newly created card.

**Comment by jenweber** [comment]
Requirements have changed and this ticket needs to be updated.
