### ISSUE TITLE
Epic: to-do for demo sandbox

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1480]
In order to have a good experience for people trying out a deployed app, we'll need to make sure a few things are true:

- [x] It is clear that entries are publicly visible, via a banner or alert of some kind. I prefer a modal because a banner would clutter the app and possibly mess up some of our layout. (1 day) https://github.com/cardstack/cardstack/issues/1489
- [x] One cannot edit the featured cards/templates from the Builder (this seems to be true already since the card catalog has its own realm, but I'm confirming w/Hassan)
- [x] Drag & drop works ok - Just a visual check
- [x] There is a guide that someone could follow
    - https://docs.cardstack.com/release/getting-started/
    - https://docs.cardstack.com/release/card-sdk/
    - https://docs.cardstack.com/release/card-sdk/schema/
- [x] There is a video that someone could follow
- [x] We communicate the advice to use Chrome on desktop - This should go in the participant invitation, most likely. (in google drive as Builder beta invitation email)
- [ ] If the app is unreachable, we know about it (could set up an uptime robot that looks at a particular card, or enable ses)
- [ ] The contents of our dev env are available in prod (aka deploy to prod, which currently has hub v1. I need to see if hub v2 requires any new env vars). (1 day) Hassan is doing this in the second week or so of April
- [x] Visual quirks from the hub v2 merge have been resolved. It has parity with the v1 app.
     - https://github.com/cardstack/cardstack/issues/1474

**Comment by dnaidionov** [comment]
Modal is fine, we should already have ready code for once-per-session modals
