### ISSUE TITLE
pgsearch refactor tracking issue

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#237]
Opening this as a place to collect notes on where we are and where we're going with the pgsearch refactor. The major goals here are

 -  allow us to consistently offer features like server-side computed properties (which can in turn power arbitrarily complex permissions, relationships, etc). By "consistently" I mean you can rely on them being present (1) in the search index, (2) in responses that bypass the search index via custom searchers, (3) in responses echoed back from writers.

 - avoid needing to always go to upstream data sources when recomputing inter-record dependencies (because they can be arbitrarily slow and some may be fragile and easy to overload).

 - make all writes (via hub:writers) also do the correct targeted update in the search index, without relying on triggering a general hub:indexers update (no more "update with hints"). This lets us maintain a clear separation between full updates (which are effectively background processing that is never in a request critical path) and ongoing concurrent writes (which are never blocked by background indexing and yet are always immediately visible in the search index).

In these notes it's useful to keep in mind three different representations for any resource:

 - the upstream format is a single json:api resource as given to us by an indexer or searcher plugin. It never has computed fields, and it can't have includes because it's only a resource, not a complete document.
 - the pristine format is a complete json:api document that is augmented with computed fields and includes.
 - the search format is a flattened representation that nests are included resources inline, flattens away the attributes and relationships POJOs, and allows field-type plugins to customize the storage format of their values for optimal searchability.

The steps here are:

 - [x] replace our built-in elasticsearch-backed index with a postgres-backed index. We need to consistently read our own writes, we don't actually depend internally on any of the things elasticsearch excels at (like deep text searches). This work is already far along on the pgsearch branch.

 - [x] refactor DocumentContext so it can run not just at indexing time, but also when assembling a response from a writer or searcher. Optimize its internals so that it can build both or either of the searchDoc and pristineDoc while caching the common work between them and not preemptively building parts it wasn't asked for.

 - [x] change hub:writers so that it uses DocumentContext to send a complete pristine document format in the response to the client, and also so that it stores the search document format directly in the search index (this allows plugins like jsonapi to drop their explicit calls to `indexers.update()`).

 - [x] change hub:searchers so it uses DocumentContext to turn any upstream documents provided by searcher plugins into pristine documents. It needs to be smart enough to not do wasted work when a searcher returns an already-pristine document (which is what happens when the request is handled by our search index). But it also needs to be able to customize responses by respecting a `?include=` query parameter. Basically it should opportunistically use what it was already given, but augment it wherever the user is asking for more.

 - [x] we have skipped tests for computed fields that can get unskipped once we've done this work.

 
 - [x] the `read` implementation in BranchUpdate should change. Today it always goes to the upstream data source, but now we can switch to the upstream_doc from pgsearch. This will require our invalidations step to get smarter
- [x] standardize all writer, searcher, and indexer APIs to represent the upstream doc as a full json:api response, not just a resource. This creates opportunities for us to better optimize when plugins happen to have extra data already available.

**Comment by ef4** [comment]
Another idea from discussion: standardized all writer, searcher, and indexer APIs to represent the upstream doc as a full json:api response, not just a resource. There are lots of opportunities to use the sideloaded includes as optimizations.

**Comment by habdelra** [comment]
done! 🎉🎉🎉
