### ISSUE TITLE
Add link-based editor for relationships

### ISSUE THREAD

**Issue by marcoow** [cardstack/cardstack#400]
We want to provide editors with a powerful and easy way to define queries and save them as _"saved searches"_. The UI for that should look like this:

![47821645-c4d47d80-dd37-11e8-87c0-48bcc2e9031e](https://user-images.githubusercontent.com/1510/47921774-b6ac6b80-deb5-11e8-8083-ac1f295a96a9.png)

The output of this will be a JSON:API query that the client can send to the backend as it is, e.g.:

```
{
  filter: {
    or: [
      { 'first-name': ['Quint'], type: 'people' },
      { type: 'articles', id: '1' }
    ]
  }
}
```

That query will be stored as the value for `@cardstack/core-types::has-many` and `@cardstack/core-types::belongs-to` fields (as opposed storing the `data` for the relation). So instead of storing something line

```json
{
  "data": {
    "id": "main-footer",
    "type": "footers"
  }
}
```

as a relationship's value we would be storing the serialized query:

```json
cards: {
  links: {
    related: "/api?filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at"
  }
}
```

So the UI shown in the above screenshot is really just an alternative to the `card-picker` that is currently used to edit fields of type `@cardstack/core-types::has-many` or `@cardstack/core-types::belongs-to`.

### Feature Spec

Each condition is based on a particular field with a particular type (String, Number/Date, Enumerable). Depending on the type of the field, the potential conditions for the field are:

* String: is, not, includes, does not contain, starts with, ends with (the kind of comparison to apply will be chosen via a `<select>` box, the value to compare to is put in via a `<input type="text">`)
* Number/Date: is, not, greater than, less than, greater or equal, less or equal, between (as for String, the kind of comparison to apply will be chosen via a `<select>` box, the value to compare to is put in via a `<input type="text">`)
* Enumerable: is, not, includes
  * For types that imply 2 values:
    * between (this would be another option in the select box for selecting the kind of comparison, the values to compare to are then put in via 2 `<input type="text">`)
    * one of: (this would be another option in the select box for selecting the kind of comparison, the values to compare to are then put in via a `<input type="text">` as a comma-separated list - we will improve the UI for that in a follow-up issue)

The output of the component is a JSON:API-compatible query filter such as:

```js
{
  filter: {
    or: [
      { 'first-name': ['Quint'], type: 'people' },
      { type: 'articles', id: '1' }
    ]
  }
}
```

that will be stored as

```
{
  links: {
    related: '/api??filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at'
  }
}
```

for a `@cardstack/core-types::has-many` or `@cardstack/core-types::belongs-to` field.

### TODO

- [ ] create new editor UI for relationships that works for relationships that are defined via `related` links; the link as such is the input for the editor then
- [ ] store the specified query as `related` link back in the relationship; this is done by assigning a `cardstack-queries` resource with the serialized filter set as its `id` as described in #411 

### Open Questions

- [x] is storing the serialized query definition in the field actually what we want or is there a better way?
- [ ] the available fields to filter on (_"Card Type"_, _"Published Date"_, _"Tags"_ in the above screenshot) would have to be defined somewhere, together with their possible values (e.g. all instances of the `Tag` card being possible values for the _"Tags"_ field) - this could be done via options passed to the editor or potentially elsewhere

**This depends on cardstack/cardstack#411 that will allow persisting relationships as `links` as opposed to `data` only.**

**Comment by marcoow** [comment]
@bagby assigned you as you were originally assigned to cardstack/deck#236 but I don't think there's anything left to do in deck.

**Comment by marcoow** [comment]
@ef4: can you check whether the above makes sense from your perspective? I'm not sure storing the search definition as serialized JSON is great but I think a dedicated field type is the best way to make this easily usable for card authors and I think in this case we sort of have to store the complete query in one field?

**Comment by ef4** [comment]
This touches on some very general purpose capability that will be great to have. So I have some detailed design thoughts:

## Query Format

We already have a standard query format, so please don't invent a new one. The best place to see what it supports is probably [these tests](https://github.com/cardstack/cardstack/blob/adbcc96d209ae2fb7df0127ea5b7366dda2f7354/packages/pgsearch/node-tests/searcher-test.js). Each place you see a call to `searcher.search()` in there, the third argument is a query. Example queries from that test suite:

```js
{
  filter: {
    id: '1',
    type: ['articles', 'people']
  }
}
```

```js
{
      filter: {
        type: ['articles', 'people']
      },
      sort: '-type'
}
```

```js
{
  filter: {
        or: [
          { 'first-name': ['Quint'], type: 'people' },
          { type: 'articles', id: '1' }
        ]
  }
}
```

```js
{
      filter: { type: 'comments' },
      page: {
        size: 7,
        cursor: response.meta.page.cursor
      }
 }
```

We can make changes the format if you find a need, but take this as a starting point.

## Query Serialization into URLs

We use `qs` for deserializing these queries out of URLs. So 

```
GET /api?filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at
```

represents the query:

```js
{ filter:
   { type: [ 'posts', 'events' ],
     category: [ 'crypto', 'engineering' ] },
  page: { size: '4' },
  sort: '-updated-at' 
}
```

And we do the same thing for URLs like `/api/articles?...`, but in that case there's an additional implied `type` filter that gets added to the query, because of the type in the URL path.

## Queries as JSON:API relationships

I would like to align this work with JSON:API relationships. For example, we can represent the query in its serialized URL form within `links`:

```js
{
  data: {
    type: 'pages',
    id: '1',
    relationships: {
      featuredCards: {
        links: {
          related: "/api?filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at"
        }
      }
    }
  }
}
```

Then we will later be able to make the Hub smart about pre-filling-in the data for these relationships, so that when somebody fetches the page back out, they can get:

```js
{
  data: {
    type: 'pages',
    id: '1',
    relationships: {
      featuredCards: {
        links: {
          related: "/api?filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at"
        },
        data: [ { type: 'events', id: '123'  }]
      }
    }
  },
  included: [
    {
      type: 'events',
      id: '123',
      attributes: {
         title: "Some Event"
      }
    }
  ]
}
```

I think we don't actually want a new field-type here, I think this is instead a new feature added to `@cardstack/core-types::has-many` and `@cardstack/core-types::belongs-to`. The way it would work is, when you save a relationship field containing `links`, the `links` takes precedences over any `data` (which would be ignored -- we only store `links` in the data store).

**Comment by marcoow** [comment]
Ok, that makes sense - so I think what we want here is sort of an alternative field editor for `@cardstack/core-types::has-many` or `@cardstack/core-types::belongs-to` fields. I'll update the original issue description.

**Comment by bagby** [comment]
@marcoow @ef4 a couple of comments/questions regarding the design changes:

* I thought part of the original intent of this was to be able to have _saved_, _named_ searches (hence the "Name your Search" text field). If this is to become simply a field editor and *not* a new field type, 
there's no affordance to store a name for the search.
* Given the design, there's not really a lot of space in the right rail to accommodate it, so it would have to be some sort of modal/popup/flyout thing, for which we have no UI designed. I can happily make something reasonably suitable as a first pass.
* I'm having trouble visualizing how a `@cardstack/core-types::has-many` would utilize this, is the idea that you could have multiple searches?

There's certainly enough here for me to get started, and perhaps the details will tease themselves out along the way, I just wanted to make sure we are more or less on the same page.

**Comment by marcoow** [comment]
@bagby: I extracted the foundation for this (and other things) into its own issue: #411

**Comment by ef4** [comment]
> I thought part of the original intent of this was to be able to have saved, named searches (hence the "Name your Search" text field). If this is to become simply a field editor and not a new field type,
there's no affordance to store a name for the search.

With this feature, you could just make a SavedSearches content-type with a title field and a results field that uses `links.related` to store the query. But you could also make lots of other things. It's very general.

> I'm having trouble visualizing how a @cardstack/core-types::has-many would utilize this, is the idea that you could have multiple searches?

No, the contents of the has-many are filled in by (one) query on demand.

Instead of saying "my `relatedCards` are `{ data: [{type: 'articles', id: 1}, { type: 'articles', id: 2 }] }` (meaning those two exact cards, hand-chosen), you could say "my `relatedCards` are `{ links: { related: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated' } }` (meaning "the three newest articles about Bagby").

Since we already have the ability to choose a custom editor component per field (I think you added that), it will now be possible to offer an exact picker for fields where we still want that, a query builder component for fields where we want that, and presumably some combined component that can switch between both where we want users to have either option.

**Comment by bagby** [comment]
> the contents of this has-many are all cards that match this query

@marcoow ok *that* makes sense to me now. I believe @ef4 said basically the same thing.

So this is a multi-parter then:

1. Allow `has-many` relationships to be represented as `links` rather than `data`, which would automagically be "deserialized" as `data` when performing a `GET` (which is #411).
2. Allow specifying a `has-many` relationship in a `POST/PATCH` request as a query (using our existing Hub query DSL) that would then be serialized into the `links` above.
3. Create a custom query editor whose output would be the query object passed into the `POST/PATCH` above.

Parts 2 and 3 don't have specific issues around them yet, but is this more along the lines of what we're thinking?

**Comment by marcoow** [comment]
Hm, the question how these relationships should be updated is a pretty good one actually 🤔 I just had a look at the [relevant section of JSON:API spec](https://jsonapi.org/format/#crud-updating-relationships) and that says relationships **must** be updated via `data` but that wouldn't work in this case of course.

I think we have 2 options here:

* either we allow relationships to be updated via `links: { related: …` as well, moving away from the JSON:API spec a bit then
* or we invent our own thing, e.g. allowing to update relationships by passing a `filter`, e.g. something like this:

```
PATCH /api/articles/1
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        filter: {
          {
            type: ['articles'],
            category: ['crypto', 'engineering']
          }
        }
      }
    }
  }
}
```

Maybe we could implement that as a [JSON:API extension](https://jsonapi.org/extensions/), although the extension system is not stable yet.

Either way, I think making sure we can set a `links`-only relationship via JSON:API should be part of #411 as it is part of the work that needs to be done to unlock the other issues that depend on this.

@ef4: do you have thoughts on that?

**Comment by marcoow** [comment]
Yeah, I'm not really sure what the best way to get this JSON:API compliant is - might actually be using the (not-yet-stable) extensions mechanism. It'd be really good to get some input from @ef4 before planning.

**Comment by marcoow** [comment]
I guess we could potentially also make these relationships editable by treating the filter as an attribute of the relationship itself. Then defining the filter for a relationship would be something like

```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "filter": "<serialized-filter>"
  }
}
```

although this is also not strictly JSON:API compliant.

**Comment by ef4** [comment]
That is a good catch. I was indeed assuming we could submit `links.related` in a POST or PATCH. But I think there is a solution here that is compliant. When in doubt, always add another kind of resource. 😛

First, remember that there server is free to modify the data you submit: what you get back may be different than what you submitted.

Then, consider that we could submit:

```
PATCH /api/articles/1
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        data: [{
          {
            type: 'cardstack-queries',
            id: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
          }
        }]
      }
    }
  }
}
```

To which the server could respond:

```js
200 OK
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        links: {
          related: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
        },
        data: [{
          {
            type: 'articles'
            id: '123'
          },
          {
             type: 'articles',
             id: '456'
          }
        }]
      }
    }
  }
}
```

The `cardstack-queries` type would be entirely virtual. We would not actually have a model or schema or store it in any data store. And as long as we encode the query as its ID, we don't need to reach for json:api operations. We can "create" a new one simply by referring to it (it's content addressable).

One thing to remember is that we should follow the arity of the underlying relationship, so if you're saving a has-many vs a belongs-to you are submitting slightly different format:

```js
relationships: {
      relatedArticles: {
        // notice this one is plural
        data: [{
          {
            type: 'cardstack-queries'
            id: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
          }
        }]
      },
      primaryArticle: {
         // and this one is singular
         data: {
           type: 'cardstack-queries',
           id: '/api?filter[type]=articles&sort=-popular&page[size]=1'
         }
      }
    }
  }
}
```

This means it would technically be possible cram _multiple_ cardstack-queries into one has-many, but I think we should reject that with a 422.

**Comment by marcoow** [comment]
As discussed in the planning, we think we need something like this:

```
data: {
    type: 'query', // special content type
    id: '1',
    attributes: {
      filter: {  // special field type
        type: 'articles'
      }
    },
    relationships: {
      contents: {
        links: {
          related: '/api?filter…'
        },
        data: [{
          {
            type: 'atricles',
            id: '1'
          }
        }]
      }
    }
  }

hub.cardsQuery.contents
```

**Comment by ef4** [comment]
@bagby pointed out a good idea, which is that we may be able to use the `meta` on relationships to hold the query, rather than needing the special cardstack-queries type.

```
PATCH /api/articles/1
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        meta: {
          cardstack-query: {
            filter: {
              type: "articles", 
            },
            q: "Bagby",
            page: {
              size: 3, 
              sort: "-updated"
            }
          }
        }
      }
    }
  }
}
```

If the spec allowed posting back `meta` like this, it would avoid the need to have a different representation in GET vs POST/PATCH
