### ISSUE TITLE
Allow relationships to be stored as links (as opposed to data)

### ISSUE THREAD

**Issue by marcoow** [cardstack/cardstack#411]
We would like to be able to define relationships as filters (as opposed to a concrete `type`/`id` pair in the case of `belongs-to` or a list of `type`/`id` pairs in the case of `has-many` relationships). This would allow making the contents of a relationship dynamic (e.g. _"the latest 5 articles sorted by descending publication date"_).

That would mean that instead of storing e.g.

```
{
  data: [
    { type: 'some-card-type', id: 'a' },
    { type: 'some-card-type', id: 'b' },
    { type: 'some-card-type', id: 'c' }
  ]
}
```

as the value of a `has-many` relationship, we would be storing something like this:

```
{
  links: {
    related: '/api??filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at'
  }
}
```

This is [equally valid JSON:API](https://jsonapi.org/format/#document-resource-object-relationships). For a relationship that only stores the `links`, the server could even go ahead and add the `data` in the response to side-load the relationships value at the time when the parent resource was requested:

```
{
  links: {
    related: '/api??filter%5Btype%5D%5B0%5D=posts&filter%5Btype%5D%5B1%5D=events&filter%5Bcategory%5D%5B0%5D=crypto&filter%5Bcategory%5D%5B1%5D=engineering&page%5Bsize%5D=4&sort=-updated-at'
  },
  data: [
    { type: 'some-card-type', id: 'a' },
    { type: 'some-card-type', id: 'b' },
    { type: 'some-card-type', id: 'c' }
  ]
}
```

As relationship links are not writable as per the JSON:API spec, we will apply a special mechanism for allowing the client to define the filter that is to be applied for a particular relationship. Instead of writing the `related` link directly, we will write to the `data` of the relationship as usual but set a special resource as the relationship's content:

```
PATCH /api/articles/1
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        data: [{
          {
            type: 'cardstack-queries',
            id: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
          }
        }]
      }
    }
  }
}
```

The `cardstack-queries` resource type does not actually exist as a model neither on the server nor the client and is only used for transferring the filter definition from the client to the server. Likewise is the fact that the filter definition is encoded in the `id` only due to the fact that this is the only way to make this JSON:API compliant and not treated as the actual ID for the resource (which is also purely virtual as described above).

The response for the request is this then:

```
200 OK
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        links: {
          related: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
        }
      }
    }
  }
}
```

The virtual `cardstack-queries` resource is gone and the filter definition that was sent in the `id` in the `PATCH` request has been applied to the relationship's `related` link. As described above, the relationship could even contain the concrete resources that match the query **in addition** to the `related` link:

```
200 OK
{
  data: {
    type: 'articles',
    id: '1',
    attributes: {
      …
    },
    relationships: {
      relatedArticles: {
        links: {
          related: '/api?filter[type]=articles&q=Bagby&page[size]=3&sort=-updated'
        },
        data: [{
          {
            type: 'articles'
            id: '123'
          },
          {
             type: 'articles',
             id: '456'
          }
        }]
      }
    }
  }
}
```

### TODO

- [ ] allow `links` as well as `data` for the [`has-many` field type](https://github.com/cardstack/cardstack/blob/master/packages/core-types/cardstack/field-types/has-many.js) but not both at the same time
- [ ] allow `links` as well as `data` for the [`belongs-to` field type](https://github.com/cardstack/cardstack/blob/master/packages/core-types/cardstack/field-types/belongs-to.js) but not both at the same time; the `related` link of a `belongs-to` **must** limit the result size to 1 (e.g. by using `page[size]=1`)
- [ ] allow updating this new kind of relationships as described above
- [ ] possibly the previous changes make adoptions elsewhere in the hub necessary
- [ ] we need to revisit the invalidation logic in the hub so that we correctly invalidate relationships that are queries (that's a separate issue though; I'd suggest this TODO is complete when we have a follow-up issue with concrete steps for adapting the invalidation logic)
