### ISSUE TITLE
The git datasource needs to reuse a cloned remote repo when the hub is restarted

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#455]
Currently when you have your hub configured to use the git datasource with a remote it will successfully clone the remote repo into a known location. This clone will then essentially be a "local cache" of the repo.

If you then restart your hub it complains that the folder already exists and is not empty. This is likely because its just trying to clone again instead of using the existing folder/repo and pulling updates.

The relevant code is here: https://github.com/cardstack/cardstack/blob/master/packages/git/service.js#L53-L70

## Todo
- [x] update the code to reuse the existing repo if the folder exists
- [ ] if you are using the existing repo you should make sure to pull changes
- [x] if the pull fails it is probably safe to delete the repo and continue with the clone semantics
  - this is because the local repo is just a cache and all changes are made to the remote first and then pulled to update the local repo
