### ISSUE TITLE
Bottom Edge - Card Selection Context as a result of Cardpicker action

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#458]
This is the initial Issue to start off the implementation of the bottom edge redesign. This is a large task so it will be broken down into distinct parts. 

The bottom edge is also intended to be stateful, and display different information based on the context that it is initialised from. For more information check out [this User Story](https://trello.com/c/EuHyTypr/102-bottom-edge-should-be-aware-of-calling-context-and-modify-its-behavior-accordingly). This issue deals with the use case of being opened **When called from the editor (the right edge) to pick the card or asset** and will only implement the current functionality of the card picker. Added functionality will be added in future issues.

This issue supersedes #439 as the initial implementation issue

Currently the bottom edge has been implemented as a fixed height toolbar. The new implementation allows for the bottom edge to toggle between a fixed height toolbar and a fullscreen view.

<img width="953" alt="screenshot 2018-11-22 at 12 24 55" src="https://user-images.githubusercontent.com/594890/48902823-a999f100-ee51-11e8-8466-78ba37e75dd3.png">

Full Screen State.
<img width="1049" alt="screenshot 2018-11-22 at 12 18 34" src="https://user-images.githubusercontent.com/594890/48902693-38f2d480-ee51-11e8-8a68-232afc019849.png">

**Please note:** This screenshot is slightly different from the original designs and is intended to show **only the features that are relevant to this Issue**. Please consult the original designs to get measurements for padding and margins: https://trello.com/c/UQCeV9Ep/43-latest-sketch-files

### Todo
- [ ] Implement "expand to full screen" button
- [ ] Implement the styles for the based on the new designs
- [ ] If possible (and time permits) remove the "show more" button from the current implementation and implement infinite scroll

**Comment by jorgelainfiesta** [comment]
We'll introduce an intermediary issue to just restyle the bottom edge on its current state (card picker)
