### ISSUE TITLE
Implement field-level full text search capabilities

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#464]
To see the origin of this issue look at the discussion on this pr (and the particular linked comment) https://github.com/cardstack/cardstack/pull/445#issuecomment-441273506

The current behaviour of the filtering functionality of Cardstack essentially does a "full-text search" on a particular field. For example: When you do `?filter[title]=ember` you get a full-text search against the title field, and you will match titles like "About ember".

This issue aims to make the full-text search on filter more explicit as a "opt in" functionality. For example:  `?filter[title]=ember` should do an exact match and we would introduce `?filter[title][contains-text]=ember` for when you really want the full-text search.

If we have this information on a field-level then this will allow us to be a bit smarter about building indexes on a field-by-field basis only when required. This prevents us from storing (or on the fly computing) field-level indexes on **every** field and will help to improve write performance of documents and storage size of the indexes.

## Todo
- [ ] add `fullTextSearchable` attribute to a field 
- [ ] Invert the default behaviour of `?filter[title]=ember` so that it does an **exact** match against the title
- [ ] Add functionlity to "opt in" to a full-text filter: `?filter[title][contains-text]=ember`

## Open questions
- [ ] Is the optimisation of building an Index ahead of time for the field-level full-text search part of the initial implementation?
