### ISSUE TITLE
Implement configuration to be able to chose which fields are `searchable`

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#465]
This work has been started in https://github.com/cardstack/cardstack/pull/445 and this issue is intended to cover the functionality of that work-in-progress implementation which was originally intended to solve #396

This issue concerns the ability to be able to **filter** a document based on the value of its attributes. The ability to filter a document by a particular attribute is governed by the presence of that attribute in the `searchDoc` in the DocumentContext.

## Todo: 
- [ ] make sure that if the `searchable` flag of an attribute is false it does not make into the searchDoc (see the tests in the linked PR)
- [ ] make sure that the `searchable` flag affects relationships as well as it does other field types
- [ ] make sure the functionality of the `searchable` flag works as expected with nested relationships
