### ISSUE TITLE
Right Edge: Confirm before exiting Edit mode

### ISSUE THREAD

**Issue by jorgelainfiesta** [cardstack/cardstack#474]
If current changes are not saved when the user is trying to exit edit mode, the system should display a dialog where user would choose whether to save or discard the changes.

Exiting the edit mode can occur if the user attempts to:

- Toggle the editor switch off
- Navigate to another (nested) card
- Close the browser tab

In case the event is triggered by the **editor switch**:  the user should be prompted with the following confirmation: 

<img width="423" alt="screen shot 2018-11-27 at 3 21 34 pm" src="https://user-images.githubusercontent.com/4451393/49087793-2c5aeb80-f258-11e8-8017-471565950a4f.png">

In case the event is triggered by the **navigating to another card**:  the user should be prompted with the following confirmation (notice the copy changes): 
<img width="431" alt="screen shot 2018-11-27 at 3 18 27 pm" src="https://user-images.githubusercontent.com/4451393/49087624-c1111980-f257-11e8-8917-7371f206c993.png">

In case the user attempts to **close the browser window**, a system dialog should be shown. We can make use of `onbeforeunload` for this purpose. 

### Tasks:
- [x] Confirm copy of dialog in case of navigaton to another card with @dnaidionov 
- [ ] Write dialog styles and logic
- [ ] Implement system dialog.
- [ ] Tests

**Comment by dnaidionov** [comment]
copy lgtm
