### ISSUE TITLE
Query-based field editor UI intended to be used for linked cards

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#507]
This Issue represents the start of the **UI elements** that are described in https://github.com/cardstack/cardstack/issues/400. This editor should serialise down to a object field type (`@cardstack/core-types::any`) until #400 is done.

![47821645-c4d47d80-dd37-11e8-87c0-48bcc2e9031e](https://user-images.githubusercontent.com/1510/47921774-b6ac6b80-deb5-11e8-8083-ac1f295a96a9.png)

The output of this picture as a JS object would be: 

```javascript
{
  filter: {
    and: [
      {
        'published-date': {
          range: {
            gte: '2018-11-10 10:10:10',
            lt: '2018-12-10 10:10:10'
          }
        }
      },
      {
        type: 'articles'
      }
    ]
  }
}
```
### Todo

- [ ] make the `all filters` dropdown control the and/or nature of the filter query
- [ ] add a card type dropdown that has all the available types (you know about) to filter against
  - there is some logic in the tools package for the create card view that should be copied for this dropdown
- [ ] have field drop downs limited to only the fields available to the currently selected card type
  - if no card type is selected then field dropdowns should contain all fields

### Open Questions

- [ ] How does one query an array field to "include" something? e.g. how do we achieve the `Tags` includes `dev` in the example above
- [ ] do we need to have "Card type" as a specific type of filter?
  - I was thinking that you might want a "choice" after clicking the `+ Add` button that asked if you wanted to add a "Card type filter" or a "Field filter"
  - The alternative is to just have it all in one dropdown but I wonder if that's potentially a bad UX because until you add a Card type filter **all possible fields** should show up in the dropdown
  - Do we have any UX design thought around this?
- [ ] how does this system know what type of comparisions are available for each type?
  - Do we just support "singular" vs "collection" differences? i.e. when you know the field is a `belongs-to` then you can show `includes` in the dropdown
