### ISSUE TITLE
Make the branch-picker decide what branch the current edit is going to apply to

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#508]
The hub should have a full understanding of the concept of a `targetBranch` when saving a change. This change should make it so that the branch picker in the tools (right edge) allows you to chose which branch is being targeted by the changes.

**Note:** this issues does **not** cover displaying the contents of different branches in the application. See Issue #509  for that part of that implementation.

![screenshot 2018-12-07 at 11 39 51](https://user-images.githubusercontent.com/594890/49645716-dc78e300-fa14-11e8-81f6-9c0ffffb212d.png)

### Todo

- [ ] Add the branch-picker dropdown back into the tools
- [ ] allow the branch-picker to be able to see all current branches
- [ ] allow the branch-picker to be able to create a new branch name
- [ ] make sure the targetBranch is communicated to the server as part of the POST/PATCH commands
- [ ] if the POST/PATCH command fails we need to show an error to the user
  - this covers the case where the user doesn't have permission to push to master

### Open Questions

- [ ] Do we need to do anything special to **create** the branch before we target it? or do we think that the git datasource should be able to take care of this because it knows the current commit sha?
