### ISSUE TITLE
Make it so we can see different content based on the currently selected branch

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#509]
![screenshot 2018-12-07 at 11 39 51](https://user-images.githubusercontent.com/594890/49645716-dc78e300-fa14-11e8-81f6-9c0ffffb212d.png)

The hub already supports a `?branch=` query parameter and there is a chance that it already works (although in a quick test it didn't work on one of our test applications). This issue covers making sure that the query param works and implementing the branch picker that is hooked into that query param.

The branch query param is a special case where it doesn't need a prefix like other queryParams in the new hub routing system i.e. `https://<application domain>/blogs/chris?branch=patch-01` should make the hub display the contents from branch named `patch-01` 

### Todo

- [x] Add the branch-picker dropdown back into the tools
- [x] allow the branch-picker to be able to see all current branches
- [x] make it so that when the branch-picker changes it changes the `?branch=` query param
- [x] Make sure the data service includes the branch query param in the JSON:API query
- [x] Make sure the searcher (or maybe jsonapi middleware) is passed the branch from the right place in the query params
- [x] Make sure the right data is passed back to the end user seeing as the searcher should be doing most of the heavy lifting
  - This is probably all already implemented, we just need to essentially write glue code and ensure that things are working as expected

### Open questions

- [x] Is it possible to have certain query params always available in the new routing implementation? i.e. params are provided by the hub package and therefore are always available to any Cardstack application - Answer: branch is a special case 👍

**Comment by mansona** [comment]
There is a chance that this already works. 

The `branch` query param is a **special case** where it doesn't need a prefix i.e. `https://<application domain>/blogs/chris?branch=patch-01`

**Comment by mansona** [comment]
I would consider the work on this now done 🎉 that is of course if we're happy with the implementation of each of the PRs

The 3 relevant PRs that have this implementation are https://github.com/cardstack/cardstack/pull/531 #534 and #535. Once they are merged then we are done with the first pass of this implementation 👍

**Comment by marcoow** [comment]
@mansona I think this is done now?

**Comment by mansona** [comment]
@marcoow yes 👍
