### ISSUE TITLE
Tracking issue - what's needed to sync two hubs over hyperledger via git without github

### ISSUE THREAD

**Issue by alexspeller** [cardstack/cardstack#663]
Here's what needs to be done to achieve this:

- [ ] Figure out how to have branches or probably more like tags. This is going to be something like a hash of some kind of string. So take e.g. `cardstack#master`, hash that to get a state address, store the name at the state address (as the hash won't be reversible probably), verify that in the processor, and store a pointer to the latest commit
- [ ] Ensure incremental cloning, so cloning a repo doesn't have to download everything each time
- [ ] Figure out automation so new commits are downloaded on a trigger instead of manually
- [ ] Figure out the merge story - so if it's "sync", you're probably going to want to pull-in changes from a remote repo instead of just have an exact copy that keeps up to date with it
- [ ] Probably some more actual security, e.g.:
  - [ ] The handler should download blobs and actively verify each commit that the commit is the right one for a given state address
  - [ ] Figure out POW instead of just using fake demo functionality
  - [ ] Require key to post to tags
