### ISSUE TITLE
Query-based relationships

### ISSUE THREAD

**Issue by bagby** [cardstack/cardstack#739]
This issue is based on #400, #411, and #507 

Basically, we want to have a way to have relationships (both `has-many` and `belongs-to`) that are based not on specific models, but on a query, utilizing our existing query DSL. An example would be a `homepage` card with a collection of recent articles sorted by `published-date`, and a "top story" article based on view count.

This issue can be broken up into the following:

* [x] implement a `JSONAPIFactory` method that defines a query-based relationship, and that will fetch the related models at the time of the request (implemented in #736)
* [x] provide the ability to programmatically create a query-based relationship (described in #411)
* [ ] implement a field editor that allows you to create a query-based relationship via the UI (described in #507)
* [ ] fetch the related models at the time the query-based relationship is created, via the indexer, and store in the index
* [ ] provide a mechanism for invalidating the indexed models
