### ISSUE TITLE
Cardhost Epic - add CSS theme capabilities

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#998]
To-do:
- [x] add a dropdown to the right edge, with 2 options, "Cardstack Theme"  and "Custom Theme." Cardstack Theme should be the default selected. (Jen) (finalized requirements in #1079)
- [x] create a layout page for the Card in css editing mode (#1082)
- [x] When you choose Custom Theme, open up the editor pane (no animation)
- [x] Render any existing Card CSS from the Card document
- [x] Show the Card markup in the HTML code editor. Should be readonly.
- [x] If you edit the CSS, the view updates (but does not persist)
- [x] Draw the rest of the owl - persist CSS. (Meet w/Hassan. See work already done here https://github.com/cardstack/cardstack/pull/979)
- [x] Write CSS (Meet w/Burcu to make sure we use the CSS utility classes, and for review)
- [x] Write tests
- [x] user testing & iteration
- [x] reviews w/Chris, Dmitry, Gardella

Side quests
- [x] test accessibility & fix any issues
- [x] Animate within cardhost
- [ ] extract animations into boxel (meet with Will)
- [ ] implement animation between right edge and the code pane, where the code pane grabs visual focus
- [x] Choose "Dock Right" or "Dock Bottom" to change the layout of the code editor pane
- [ ] animate dock right vs dock bottom
- [x] Choose Card Size or Full Size to change card preview width #1130 #1138
- [x] animate Card Size vs Full Size #1138
- [x] Add drag/resize handle to change code editor width/height

Our questions:
- does/will the markup for a card be part of the card document/record, or do we grab it from the DOM?
- how to do transitions between views using boxel?
- how to persist CSS?
- how to populate default classes in the css
- when you "customize," do you edit existing standard theme CSS, start from a blank slate, or override? Previous conversation w/Dmitry was that we override. Easiest technically, most likely? Is it?
- How to best handle CSS scoping
- Should CSS syntax errors block saving? Alternative, warning flow? "Errors have been detected in your CSS. Are you sure you want to save?"
- How to deal with styling conditional states? For example, something wrapped in `{{#if}}` won't be in the DOM. 
- Features to handle state? i.e. visited, hover, etc.
- How interactive is the Card when you are viewing the CSS. Imagine that my Card is a form. I want to see how the dropdown menu looks and style it.

Reminders to ourselves:
- Be mindful of what we show to the user vs what is reality. We want things to be simple for the user, not complex like what we are doing behind the scenes.
- Think about the concept of a translation layer

**Comment by jenweber** [comment]
I'm throwing this back into "todo" since most topics that remain are animation related, or not likely for this sprint

**Comment by jenweber** [comment]
Closing this issue, since remaining work is about animation and should be handled together with other app animations.
